### ISSUE TITLE
Parallel support for bootstrapping

### ISSUE THREAD

**Issue by Ax3man** [lamho86/phylolm#10]
Hi to you both, and thanks for this great package. I'm finding it very useful.

I'm in the process of incorporating `phylolm` in the `phylopath` package for a couple a reasons, one of which is the performance on large trees. A slow performing part of the function is, however, if one wants to estimate confidence intervals using the `boot` argument (which I presume is the recommended method for both `phylolm` and `phyloglm`). This seems like an "embarrassingly parallel problem" to me and I was wondering whether you have considered to include parallel support for this?

It would basically involve parallelizing the `for (i in 1:boot) { }` part of the two functions, and should be relatively straight-forward. I would be happy to prepare a pull request for that, but it may take me a couple of weeks to get to it, since I'm nearing the final stages of my thesis work.

Thanks again.

**Comment by cecileane** [comment]
Yes indeed, this is an embarrassingly parallelizable task. If you could prepare a pull request, that would be great!

**Comment by cecileane** [comment]
wonderful, thanks a bunch!
