### ISSUE TITLE
How to explain the phylolm results

### ISSUE THREAD

**Issue by lychen83** [lamho86/phylolm#19]
Hello,

I am trying to find out the genes with expression level correlated to the trait (coded as 0 and 1) with phylolm.  I have one question.
When I run the phylolm using following command:
library('ape')
library('phylolm')
setwd("path)
getwd()
samples = read.table("expression_trait_file",row.names=1)
tree = read.nexus("tree", tree.names = NULL, force.multi = FALSE)
fit = phyloglm(formula=pigment~tpm, data=samples, phy=tree, method = ("logistic_MPLE"), boot = 0)
summary(fit)
coef(fit)
vcov(fit)

I got results as following:

> summary(fit)

Call:
phyloglm(formula = pigment ~ tpm, data = samples, phy = tree, 
    method = ("logistic_MPLE"), boot = 0)
       AIC     logLik Pen.logLik 
     44.35     -19.17     -16.78 

Method: logistic_MPLE
Mean tip height: 0.3558203
Parameter estimate(s):
alpha: 2.787424 

Coefficients:
             Estimate    StdErr z.value p.value  
(Intercept) -2.091304  1.114385 -1.8766 0.06057 .
tpm          0.142301  0.099049  1.4367 0.15081  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Note: Wald-type p-values for coefficients, conditional on alpha=2.787424

> coef(fit)
(Intercept)         tpm 
 -2.0913038   0.1423013 
> vcov(fit)
            (Intercept)          tpm
(Intercept)  1.24185403 -0.062150513
tpm         -0.06215051  0.009810609

Could you kindly me let me know how I can know if the gene expression is significantly correlated to the trait (coded a 0 and 1) from the output?   In other words, could you kindly tell me how to explain the results?
Thank you very much.

Best regards,

Lingyun

**Comment by cecileane** [comment]
your p-value is 0.06057: it seems like there is marginal significance.

**Comment by cecileane** [comment]
your p-value is 0.15081: it seems that there is no evidence of a correlation.
