### ISSUE TITLE
Post hoc test in phyloglm?

### ISSUE THREAD

**Issue by rosbakh** [lamho86/phylolm#22]
Hello,

I was wondering if you implemented any post hoc test in your wonderful package?

I run several pGLMs (method = poisson_GEE), in which I compare seed germination response of several species belonging to one particular ecological group to a given experimental treatment, i.e. germination response ~ group. Everything works just fine and in the output I see that the groups respond differently to the treatments. In the next step I would like to run a post hoc test, in order to find out the differences among the groups. I have tried 'standard' packages, such as multcomp, but they do not work with pGLMS, because the output belongs to the class 'phyloglm', which is apparently not supported by the existing packages.

I would appreciate any advice on this issue.

Thanks in advance!
Sergey

**Comment by cecileane** [comment]
This is a very good point! It would be great to make it possible for `multcomp` to use the output of `phyloglm`. I am not familiar about what `multcomp` requires, and I don't have time to take this on at the moment unfortunately.

So far, one thing you can do is relevel your group factor to change the baseline group, and then do pair-wise comparisons (between each group and the baseline). Adjustment for multiple testing would need to be done 'by hand'. 

But if someone would want to make `phyloglm` objects compatible with what `multcomp` needs, that would be awesome!

**Comment by rosbakh** [comment]
Thank you very much for your prompt response!

Yes, I was thinking about 'manual' group comparison, but wanted to do it automatically. I will try to reach out the developers of the multcomp, may be they will help.

Best,
Sergey
