### ISSUE TITLE
How to solve "Error in lenth(taxa_without_data) : could not find function "lenth""

### ISSUE THREAD

**Issue by jeagull** [lamho86/phylolm#24]
I am trying to use phylolm in the near future and I am running the example in the Rdocumentation as shown
```
set.seed(123456)
tre = rtree(50)
x = rTrait(n=1,phy=tre)
X = cbind(rep(1,50),x)
y = rbinTrait(n=1,phy=tre, beta=c(-1,0.5), alpha=1 ,X=X)
dat = data.frame(trait01 = y, predictor = x)
fit = phyloglm(trait01~predictor,phy=tre,data=dat,boot=100)
summary(fit)
coef(fit)
vcov(fit)
```
and I get the error
```
Error in lenth(taxa_without_data) : could not find function "lenth"
```
when I try to run the fit = phyloglm... bit of the code.
Can you tell me what the issue is and give me suggestions on what I can do to avoid this?

**Comment by lamho86** [comment]
Hello,

The problem should be fixed by now. Please update the lasted version.

Best,
Lam

Lam Ho | Assistant Professor
FACULTY OF SCIENCE
Department of Mathematics and Statistics
902.494.1069

Dalhousie University
dal.ca

**Comment by cecileane** [comment]
Thank you so much @jeagull for opening this issue! highly appreciated. I'm sorry for the trouble.
