### ISSUE TITLE
Back-transformation of phylogenetic logistic regression

### ISSUE THREAD

**Issue by rosbakh** [lamho86/phylolm#29]
Dear developers of the phylolm package,

I am sorry for posting this question here - I could not find any help elsewhere.
For the sake of clarity, I would like to back-transform the estimates for a phylogenetic logistic regression I run with the help of your package. When I apply the 'standard' exp () I used to use for non-phylogenetic regressions, I get meaningless results. Am I missing something? Should I back-transform the estimates differently? 

Thanks,
Sergey

**Comment by lamho86** [comment]
Hello Sergey,

I am still unsure about your question. Could you please give more details?

Lam

Lam Ho | Assistant Professor
FACULTY OF SCIENCE
Department of Mathematics and Statistics
902.494.1069

Dalhousie University
dal.ca

**Comment by rosbakh** [comment]
Hi Liam,

Sorry, I made some mistakes in the code that resulted in wrong estimates. It works well now.

Take care,
Sergey

**Comment by rosbakh** [comment]
Hi Liam,

Sorry, I made some mistakes in the code that resulted in wrong estimates. It works well now.

Take care,
Sergey
