### ISSUE TITLE
phyloglmstep

### ISSUE THREAD

**Issue by rvosa** [lamho86/phylolm#31]
I am half and half under the impression that it would be a valid and useful thing to do basically what phylostep does, but then for phyloglm's. I was therefore a bit surprised that this doesn't exist in your package. Am I missing an important reason why one couldn't do this?

If it's simply a matter that you haven't got to because it is not important for your research then I'd be happy to donate an implementation: https://github.com/naturalis/phyloglmstep/blob/master/R/phyloglmstep.R

It is literally the exact same code as phylostep except you have to pass in the arguments for phyloglm instead, and phyloglm instead of phylolm is invoked in the function body. It seems to me you can do the same AIC-based nested model comparisons so I kept that all the same.

**Comment by cecileane** [comment]
I agree! The reason is indeed a total lack of time (on my end) and the need to prioritize other projects --projects that will help students graduate, for instance.

**Comment by lamho86** [comment]
@rvosa: This should be useful. Could you create a pull request?
