### ISSUE TITLE
Alpha warning when performing phylostep/phyloglmstep

### ISSUE THREAD

**Issue by estherdr** [lamho86/phylolm#33]
For my project I used the phyloglmstep implementation presented by rvosa in the previous issue (https://github.com/naturalis/phyloglmstep/blob/master/R/phyloglmstep.R). 

During this I got the following warning:
"The estimate of ‘alpha’ (8.03841658764875) reached the upper bound (8.06867371201789). This may simply reflect a flat likelihood at large alpha values, meaning that the phylogenetic correlation is estimated to be negligible"

This warning seems to indicate that the phylogenetic component is not of major importance, which is not a huge problem in itself in my opinion. Is my opinion correct in your eyes or do you think I should avoid using results that come with this warning? 

Thank you in advance!

**Comment by lamho86** [comment]
Hello,

Your interpretation of this warning is correct. You don’t need to avoid using results that come with this warning.

best,
Lam
