### ISSUE TITLE
predict () does not work with 'phyloglm' object

### ISSUE THREAD

**Issue by rosbakh** [lamho86/phylolm#37]
Hello,

I am running phylogenetic generalized models with 'phylolm' to estimate pollen trait variability (ca. 1100 species) along environmental gradients. The 'phyloglm' function does it job nicely, but I cannot use the 'predict' function to make nice graphs. I get following error message:
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "phyloglm"  

What could be the problem?

Thanks and all the best,
Sergey

**Comment by lamho86** [comment]
Hello,

We haven't implemented 'predict' method for a phyloglm object.
