### ISSUE TITLE
What's the order of residuals in the result of phyloglm?

### ISSUE THREAD

**Issue by yuxin0406** [lamho86/phylolm#45]
Hi, 

I'm doing the logistic regression using phyloglm and method "logistic_IG10". However, when I look at the phyloglm$residuals, I find that the order of the residuals is not consistent with the order of my data in the table. And then I checked some objects like the tip.label, X and y, the result is that there are three different data orders: 1. Dataframe (known); 2. X and tip.label (known); 3. y, residuals and fittedvalue (unknown). 

So my question is what's the order of the residuals? Looking forward to your reply.

Best wishes,
Yuxin Wei

**Comment by lamho86** [comment]
Hi,

Thanks for letting us know. I have updated the repo to fix this problem.
