### ISSUE TITLE
R-squared and Adjusted R-squared

### ISSUE THREAD

**Issue by paternogbc** [lamho86/phylolm#49]
Hi, thanks a lot for keeping improving this fantastic package. 

I was wondering which method are being used to calculate R-squared and Adjusted R-squared. I checked the documentation but could not find a clear reference to the calculation method in phylolm. Since I am getting different results from the summary of phylolm and R2 calculated with the function [rr2:R2](https://www.rdocumentation.org/packages/rr2/versions/1.0.2/topics/R2), I wonder which method you are implementing in phylolm. 

I would greatly appreciate any feedback.

**Comment by paternogbc** [comment]
Many thanks for the reply!

**Comment by soungalo** [comment]
Arriving to the party a little late, but still - could you please explain what is the null model we are comparing against? Is it a model in which the response variable is solely explained by the phylogeny? e.g. a BM or OU model?
