### ISSUE TITLE
'Both' model selection gives worse results than 'forward'?

### ISSUE THREAD

**Issue by rvosa** [lamho86/phylolm#52]
Hi,

I really ought to be able to answer this question myself because I drafted the first version of phyloglmstep(), which @lamho86 then tweaked, but I'm getting results I can't yet explain. On a particular data set forward model selection is giving me pretty consistently better results than 'both'. Am I wrong in being surprised about this? I figured 'both' should be _less_ likely to get trapped in local optima? 

Rutger

**Comment by lamho86** [comment]
Hi, 

I am not surprised that forward selection can select a better model than stepwise. I don't think it happens often but it does happen sometimes. For example, if forward selection leads to a correct path to the best model, stepwise may be trapped in local optima by trying several other directions.

**Comment by rvosa** [comment]
I guess so, right? I will look more closely into which ones the 'both' is getting stuck in to see if I can make it make sense. Anyway, go ahead and close this ticket. All the best!
