### ISSUE TITLE
Interpret scale parameter when estimating dispersion in Poisson model

### ISSUE THREAD

**Issue by ashdederich** [lamho86/phylolm#59]
Hi,

I'm working on checking dispersion for my poisson models. I saw in R documentation that a summary of the ```phyloglm``` poisson model gives me a scale estimate, which is the scale parameter to estimate overdispersion.

For one of my models, I have a scale of 0.2704646 and I am unsure how to interpret it. I know that an evenly dispersed Poisson model needs to have a dispersion close to 1.  However, since scale is measuring _overdispersion_ I'm unsure if it should be close to 0 or not. How do I interpret the scale parameter, and is there a way to test if the over/underdispersion is significant or not? I was not able to use the ```dispersiontest()``` function from the AER CRAN package because it is not a glm object that the ```dispersiontest()``` function recognizes.

Additionally, are there built-in ways in ```phylolm``` for correcting for over/underdispersion?

Thank you for such a great package!
Ashley

**Comment by lamho86** [comment]
Hello Ashley,

The scale is the dispersion parameter of the Poisson model.
